TeamOHJO/Frontend

- src/pages/Accommodation/AccommodationMainImg.tsx
- src/pages/Accommodation/AccommodationRoomItem.tsx
- src/pages/Room/RoomBottomNavi.tsx
- src/pages/Room/RoomInfo.tsx
- src/pages/Room/RoomInfoText.tsx
- src/pages/Room/RoomMainImg.tsx
- src/pages/Room/RoomNavi.tsx
- src/pages/Room/RoomSelectedInfo.tsx
- src/pages/Room/RoomTitle.tsx
> [#20] 객실 상세페이지 디자인

- src/pages/WishList/WishListCard.tsx
> 위시리스트 하트 색 파랑 -> 빨강으로 변경

- index.html
- src/components/Layout/Navigation.tsx
- src/components/TopBtn/index.tsx
- src/pages/Basket/index.tsx
- src/pages/Home/HomeCard.tsx
- src/pages/MyPage/index.tsx
- src/pages/WishList/index.tsx
- 네비게이션바 디자인
close #23 
- 로그인 상태에 따라 변경되도록 구현
- 페이지에 따라 아이콘 focus
- 비로그인
- 로그인
> [#23] 네비게이션바 디자인

- src/pages/MyPage/MyPageInfo.tsx
- src/pages/MyPage/MyPageInfo/index.tsx
- src/pages/MyPage/MyPageReservation.tsx
- src/pages/MyPage/MyPageReservation/index.tsx
- src/pages/MyPage/MyPageReview.tsx
- src/pages/MyPage/MyPageReview/index.tsx
- src/pages/MyPage/MyPageSubtitle.tsx
Close #35 
혹시 마이페이지 레이아웃 작업하고 계셨던 분 있으시면 죄송합니다...
> [#35]  MyPage 폴더 내부 구조 변경

- package.json
- vite.config.ts
> [#44] https 설정 삭제

- src/@types/interface.ts
- src/api/index.ts
- src/api/type.ts
- src/components/Modal/ToastPopup.tsx
- src/pages/Login/JoinInput.tsx
- src/pages/Login/JoinTabButton.tsx
- src/pages/Login/JoinTabContent.tsx
- src/pages/Login/LoginInput.tsx
- src/pages/Login/LoginTabButton.tsx
- src/pages/Login/LoginTabContent.tsx
- src/pages/test/Test.tsx
- src/routes/MainRouter.tsx
- src/states/atom.ts
- src/utils/utils.ts
로그인/회원가입 api 연동
테스트 페이지 로그아웃 버튼 추가
- 로그인 시 쿠키 등록이 잘되는지
- 로그아웃시 쿠키 삭제가 잘되는지
- 쿠키가 없을때 로그인페이지로 이동이 잘되는지
- 기타 회원가입 로직이 잘 동작하는지
테스트 요망
close #44
> [#44] 로그인/회원가입 api 연동

- src/pages/WishList/WishListCard.tsx
> fix: 배포오류수정

- src/components/Layout/UnFooterNav.tsx
- src/pages/Accommodation/AccommodationNavi.tsx
- src/pages/Accommodation/AccommodationRoomItem.tsx
- src/pages/Accommodation/index.tsx
- src/pages/Room/RoomBottomNavi.tsx
- src/pages/Room/RoomNavi.tsx
- src/pages/Room/index.tsx
> [#79] 상세 페이지 디테일

- src/components/Layout/Footer.tsx
- src/components/Layout/Navigation.tsx
- src/pages/Home/ContentsContainer.tsx
- src/pages/Home/HomeCard.tsx
- src/pages/Home/HomeHeart.tsx
- src/pages/Home/HomeHeartToastPopUp.tsx
- src/pages/Home/HomeSwiper.tsx
- src/pages/Home/SearchBtn.tsx
- src/pages/Home/SearchModal/Calendar.tsx
- src/pages/Home/SearchModal/index.tsx
- src/routes/MainRouter.tsx
- src/utils/utils.ts
-  추가 기능 보완 및 버그 수정
- 많은 것을 했읍니다.. 
- 네비게이션 버그 수정, 로그아웃, 메인페이지 달력기능 등등 
close #66 
- 권장
확인 후 어푸르브 부탁드려용
> [#66] 추가 기능 보완 및 버그 수정

- src/pages/Home/ContentsContainer.tsx
- src/pages/MyPage/MyPageReview/MyReviewToastPopup.tsx
- src/pages/MyPage/MyPageReview/ReviewCard.tsx
- src/pages/MyPage/MyPageReview/index.tsx
> [#88]DELETE 팝업 추가가

- src/api/index.ts
- src/pages/Login/JoinTabContent.tsx
- src/pages/MyPage/MyPageInfo/PasswordSection.tsx
- src/pages/MyPage/MyPageInfo/ResignSection.tsx
- src/pages/MyPage/MyPageInfo/index.tsx
> [#95]회원탈퇴기능 추가

- src/@types/interface.ts
- src/hooks/useThrottle.tsx
- src/pages/Home/ContentsContainer.tsx
- src/pages/Home/HomeHeart.tsx
- src/pages/Home/HomeHeartToastPopUp.tsx
- src/pages/Home/MenuBar.tsx
- src/pages/Home/SearchModal/index.tsx
- src/pages/Login/JoinInput.tsx
- src/pages/Login/JoinTabContent.tsx
- src/pages/Login/LoginTabContent.tsx
- 쓰로틀링 구현 및 적용
- 페이지네이션 버그 수정
close #106 
- 적용 전
https://github.com/TeamOHJO/Frontend/assets/83493231/29842138-6550-492f-af1e-6599ca229f1b
- 적용 후
https://github.com/TeamOHJO/Frontend/assets/83493231/3884f1ab-1b40-45f8-a0e7-268ffb307a32
- 코드 (src/hooks/useThrottle.tsx)
- 적용방법
0. 커스텀훅 임포트 & 선언
2. 일반함수
4. 비동기함수
> [#106] 쓰로틀링/ 페이지네이션 버그 수정

- src/pages/Home/SearchModal/VisitorSetter.tsx
- src/pages/Home/SearchModal/index.tsx
- src/routes/MainRouter.tsx
> fix: 인원수 검색 필터링 버그 수정

- package-lock.json
- package.json
- src/@types/interface.ts
- src/components/Layout/Navigation.tsx
- src/pages/Home/ContentsContainer.tsx
- src/pages/Home/HomeCard.tsx
- src/pages/Home/MenuBar.tsx
- src/states/atom.ts
- src/utils/utils.ts
홈페이지 관련 코드 리펙토링/버그수정
close #118 
- history, https 패키지 제거
> [#118] 홈페이지 관련 코드 리펙토링/버그수정

- package-lock.json
- package.json
- src/pages/Home/ContentsContainer.tsx
- src/pages/Home/MenuBar.tsx
- src/pages/Home/SearchModal/index.tsx
- src/pages/Login/index.tsx
- src/routes/MainRouter.tsx
- src/routes/UserRouter.tsx
- src/states/atom.ts
- 유저 라우터 적용/recoil-persist 제거
close #125
> [#125] 유저 라우터 적용/recoil-persist 제거

- src/pages/Home/HomeSwiper.tsx
: 메인페이지 이미지 로딩 지연 적용
close #127 
- 권장
> refact: 메인페이지 이미지 로딩 지연 적용

- index.html
- src/pages/Home/HomeSwiper.tsx
- src/styles/reset.ts
더보기 스크롤 해결, 불필요한 웹폰트 제거
close #130 
> [#130] 더보기 스크롤 해결, 불필요한 웹폰트 제거

- index.html
- src/components/Error/index.tsx
- src/pages/Accommodation/AccommodationMainImg.tsx
- src/pages/Accommodation/AccommodationSelect.tsx
- src/pages/Accommodation/AccommodationTitle.tsx
- src/pages/Accommodation/Info/AccommodationInfo.tsx
- src/pages/Accommodation/Info/AccommodationInfoMap.tsx
- src/pages/Accommodation/Info/AccommodationInfoTag.tsx
- src/pages/Accommodation/Info/AccommodationInfoText.tsx
- src/pages/Accommodation/Review/AccommodationReview.tsx
- src/pages/Accommodation/Rooms/AccommodationRooms.tsx
- src/pages/Accommodation/Swiper/OnOpenSwiper.tsx
- src/pages/Accommodation/index.tsx
- src/pages/Room/BottomNavi/RoomBottomNavi.tsx
- src/pages/Room/Info/RoomInfo.tsx
- src/pages/Room/Info/RoomInfoTag.tsx
- src/pages/Room/Info/RoomInfoText.tsx
- src/pages/Room/RoomMainImg.tsx
- src/pages/Room/RoomSelectedInfo.tsx
- src/pages/Room/RoomTitle.tsx
- src/pages/Room/index.tsx
- src/routes/MainRouter.tsx
> refact: 스켈레톤 적용 #129

- src/pages/AddReview/AddReviewForm.tsx
> fix: 리뷰 작성시 토스트팝업 내용없는 버그 수정

- src/hooks/useInfiniteScroll.tsx
- src/pages/Home/ContentsContainer.tsx
close #139 
무한스크롤 구현했습니다.
스크롤 이벤트, 인터섹션 API 두 방식 모두 개발해봤습니다.
전자가 깔끔하게 구현되었지만 성능 상 인터섹션이 좋다는걸 알고 변경했습니다.
코드가 길어지고, 추후 프로젝트에서 쓸 수 있어서 커스텀훅으로 분리했습니다
> [feat] 무한스크롤 구현
